### DISCUSSION TITLE
下一个版本的新想法

### DISCUSSION THREAD

**Discussion by Yunxi-awa** [hect0x7/JMComic-Crawler-Python#195] [Ideas]
- [ ] **添加一个日志的开关，有时候不想输出那么多的日志**
- [ ] 可以为download_album设置返回albumDetail对象，download_batch返回albumDetail对象的列表, download_photo返回photoDetail对象。
- [ ] 将抓取的album属性自动保存在sqlite的插件

**Comment by Yunxi-awa** [comment]
> * [ ]  **添加一个日志的开关，有时候不想输出那么多的日志**
> * [ ] 可以为download_album设置返回albumDetail对象，download_batch返回albumDetail对象的列表， download_photo返回photoDetail对象。
> * [ ] 将抓取的album属性自动保存在sqlite的插件

最新发现：在文档中未标注
在option文件中输入一级log标签设置值不为None即可关闭日志
client标签中添加retry_times, 后面写重试次数即可自定义重试次数

**Comment by hect0x7** [comment]
# 添加一个日志的开关，有时候不想输出那么多的日志

这个点也很符合我的想法，jmcomic目前的版本提供以下几种日志自定义方式来解决这个问题：

- [x] 备忘：记得下个版本完善日志这块的问题

## 1. 日志完全开启/关闭

使用代码：
```
from jmcomic import disable_jm_log 
disable_jm_log()
```

使用配置：
```yml
log: false

```

## 2. 日志过滤，只保留特定topic

使用插件配置
```yml
log: true

plugins:
  after_init:
    - plugin: log_topic_filter # 日志topic过滤插件
      kwargs:
        whitelist: [ # 只保留api和html，这两个是Client发请求时会打的日志topic
          'api',
          'html',
        ]
```

## 3. 屏蔽插件的日志
给插件配置加上一个`log`配置项即可
```yml
plugins:
  after_init:
    - plugin: client_proxy # 提高移动端的请求效率的插件
      log: false # 插件自身不打印日志
      kwargs:
        proxy_client_key: cl_proxy_future
        whitelist: [ api, ]
```

## 4. 完全自定义 jmcomic 日志
参考文档：https://jmcomic.readthedocs.io/en/latest/tutorial/4_module_custom/
![image](https://github.com/hect0x7/JMComic-Crawler-Python/assets/93357912/198175d4-1d94-4664-9d1e-f7627a3bdd2c)
