### DISCUSSION TITLE
写了一个简单的WebUI

### DISCUSSION THREAD

**Discussion by Vallily** [hect0x7/JMComic-Crawler-Python#417] [UI]
还没封装，根据自己的用户体验设计了一些功能，只是这样已经看起来很爽了=w=

<a href="https://github.com/Vallily/JMComic-WebUI">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://github-readme-stats.vercel.app/api/pin/?username=Vallily&repo=JMComic-WebUI&theme=radical" />
    <source media="(prefers-color-scheme: light)" srcset="https://github-readme-stats.vercel.app/api/pin/?username=Vallily&repo=JMComic-WebUI" />
    <img alt="JMComic-WebUI Repo Card" src="https://github-readme-stats.vercel.app/api/pin/?username=Vallily&repo=JMComic-WebUI" />
  </picture>
</a>

**Comment by Jackxwb** [comment]
试用了下，处于能用，但还不算好用。看着教程写了个Docker build脚本，可以一键部署到服务器

Dockerfile
```
FROM python:3.9.22-alpine

# 先设置镜像源和安装git
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
    apk add --no-cache git

WORKDIR /app
RUN git clone https://github.com/Vallily/JMComic-WebUI.git .
# 安装 jmcomic 库，如果无法安装，请自行更换源
# RUN pip install jmcomic -i https://pypi.org/project -U
RUN pip install jmcomic -i https://mirrors.aliyun.com/pypi/simple/ -U
# 补充项目依赖
RUN pip install flask -i https://mirrors.aliyun.com/pypi/simple/ -U
CMD ["python", "app.py"]
```

docker-compose.yml
```
version: '3'
services:
  web:
    build: .
    image: jmcomic-webui:1.0
    network_mode: bridge
    restart: unless-stopped
    ports:
      - "6900:5000"
    volumes:
      - ${savePath}:/app/Archive
```

.env
```
# Stack 名称设定，可选
COMPOSE_PROJECT_NAME=jmcomic-webui
# 下来的漫画保存路径，请自行设定下载后的漫画保存路径
savePath=./save
```

保存完上面三个文件，在目录下依次运行
1. `docker compose build` 编译镜像
2. `docker compose up -d` 部署镜像

端口号 `6900` 可自行修改
后续升级，应该重新运行这两个命令应该就可以了
