### DISCUSSION TITLE
禁漫出现API域名更改/服务器内部错误？

### DISCUSSION THREAD

**Discussion by 006lp** [hect0x7/JMComic-Crawler-Python#439] [General]
### 注意事项

- [x] 提ISSUE前，请确认你已经在GitHub Issues和Discussions里搜索过类似的问题，并且没找到想要的答案。

### 你使用的是哪种方式？

Python代码

### 你的目的？

使用的[nonebot-plugin-jmdownloader](https://github.com/Misty02600/nonebot-plugin-jmdownloader)用到了API，尝试登陆时全部超时

### 你遇到的困难？

截至现在
<https://github.com/hect0x7/JMComic-Crawler-Python/blob/905f72c690da6ac03e079589bb796adc75436419/src/jmcomic/jm_config.py#L130-L133>
中所给的域名似乎全访问不了，几乎全都是`Operation timed out after 30002 milliseconds with 0 bytes received.`

### 额外信息（代码/option配置/截图等）

```
option = create_option_by_str(config_data, mode="yml")


config_data = f"""
log: {plugin_config.jmcomic_log}

client:
  impl: api
  retry_times: 1
  postman:
    meta_data:
      proxies: {plugin_config.jmcomic_proxies}

download:
  image:
    suffix: .jpg
  threading:
    image: {plugin_config.jmcomic_thread_count}

dir_rule:
  base_dir: {cache_dir}
  rule: Bd_Pid

plugins:
{login_block}
  after_photo:
    - plugin: img2pdf
      kwargs:
        pdf_dir: {cache_dir}
        filename_rule: Pid
"""
```
