### ISSUE TITLE
請問怎樣使用 find_update？

### ISSUE THREAD

**Issue by SKY42000** [hect0x7/JMComic-Crawler-Python#128]
我想知道該怎樣下載一個album中特定章節後的全部新章節。我看了usage_advanced.py和getting_started.py，但是也看不太懂該怎麼做。新手剛剛上路，謝謝。

**Comment by hect0x7** [comment]
只需要一个配置文件和两行代码：


1. 配置文件，假设叫 op.yml
```yml
plugin:
  after_init:
    - plugin: find_update
      kwargs:
        145504: 290266 # 冒号前面写 album的id，冒号后面写章节的id

```

2.  python代码
```python
import jmcomic
jmcomic.create_option('op.yml') # op.yml所在路径
```
运行上述python代码即可
