### ISSUE TITLE
[Help] 如何设置好的文件名称 可以让komga有效的识别

### ISSUE THREAD

**Issue by OxYancy** [hect0x7/JMComic-Crawler-Python#280]
### 注意事项

- [X] 提ISSUE前，请确认你已经在GitHub Issues和Discussions里搜索过类似的问题，并且没找到想要的答案。

### 你使用的是哪种方式？

Python代码

### 你的目的？

如何设置下载好的文件名称 可以让komga有效的识别
包括img 和zip格式

### 你遇到的困难？

我下载的zip全是在一个目录

### 其他信息

```yaml
  after_album:
    - plugin: zip # 压缩文件插件
      kwargs:
        # level: photo # 按照章节，一个章节一个压缩文件
        # filename_rule: Pname_Ptitle # 压缩文件的命名规则
        # filename_rule: Ptitle # 压缩文件的命名规则
        level: album
        filename_rule: Atitle # 压缩文件的命名规则
        zip_dir: C:\Users\xxxxxx\Desktop\jmcomic_down\zip
        delete_original_file: true # 压缩成功后，删除所有原文件和文件夹
```
