### ISSUE TITLE
[Help] 麻烦给一个配置文件  我下载多章节的只有第一章

### ISSUE THREAD

**Issue by OxYancy** [hect0x7/JMComic-Crawler-Python#306]
### 注意事项

- [X] 提ISSUE前，请确认你已经在GitHub Issues和Discussions里搜索过类似的问题，并且没找到想要的答案。

### 你使用的是哪种方式？

Python代码

### 你的目的？

我下载多章节的只有第一章

### 你遇到的困难？

我下载多章节的只有第一章

**Comment by hect0x7** [comment]
大概率不是配置文件的问题，麻烦给下代码和本子id，顺便确认下未登录情况下本子是否只能看一章

**Comment by hect0x7** [comment]
配置文件项目简介就有：https://jmcomic.readthedocs.io/zh-cn/latest/option_file_syntax/#

**Comment by liy93** [comment]
确实有这样的问题，使用option下载时，所有本子章节数都是 1。
option.yaml:
```
client:
  cache: null
  domain: 
    - 18comic.vip
    - 18comic.org
  impl: html
  postman:
    meta_data:
      headers: null
      impersonate: chrome110
      proxies:
        http: 192.168.3.254:7890
        https: 192.168.3.254:7890
    type: cffi
  retry_times: 5
dir_rule:
  base_dir: ```/project/jm/test
  rule: Bd_Pname
download:
  cache: true
  image:
    decode: true
    suffix: null
  threading:
    image: 30
    photo: 8
log: true
plugins:
  valid: log
version: '2.1'
```
下载代码：
```
import jmcomic

# 创建配置对象
option = jmcomic.create_option_by_file('./option.yml')
# 使用option对象来下载本子
jmcomic.download_album(422866, option)
# 等价写法: option.download_album(422866)
```

输出：
```
[2024-11-23 01:03:01] [MainThread]:【html】https://18comic.vip/album/422866
[2024-11-23 01:03:04] [MainThread]:【album.before】本子获取成功: [430371], 作者: [MANA], 章节数: [1], 总页数: [31], 标题: [[MANA] 神里綾華 1–4 (原神) [中国語] [無修正]], 关键词: ['無修正', '全彩', '劇情向', '馬尾', '巨乳', '中文']
······
```

**Comment by hect0x7** [comment]
> @hect0x7 确实有这样的问题，使用option下载时，所有本子章节数都是 1。
> 
> 版本是2.5.23
> 
> option.yaml:
> 
> ```
> client:
>   cache: null
>   domain: 
>     - 18comic.vip
>     - 18comic.org
>   impl: html
>   postman:
>     meta_data:
>       headers: null
>       impersonate: chrome110
>       proxies:
>         http: 192.168.3.254:7890
>         https: 192.168.3.254:7890
>     type: cffi
>   retry_times: 5
> dir_rule:
>   base_dir: ```/project/jm/test
>   rule: Bd_Pname
> download:
>   cache: true
>   image:
>     decode: true
>     suffix: null
>   threading:
>     image: 30
>     photo: 8
> log: true
> plugins:
>   valid: log
> version: '2.1'
> ```
> 
> 下载代码：
> 
> ```
> import jmcomic
> 
> # 创建配置对象
> option = jmcomic.create_option_by_file('./option.yml')
> # 使用option对象来下载本子
> jmcomic.download_album(422866, option)
> # 等价写法: option.download_album(422866)
> ```
> 
> 输出：
> 
> ```
> [2024-11-23 01:03:01] [MainThread]:【html】https://18comic.vip/album/422866
> [2024-11-23 01:03:04] [MainThread]:【album.before】本子获取成功: [430371], 作者: [MANA], 章节数: [1], 总页数: [31], 标题: [[MANA] 神里綾華 1–4 (原神) [中国語] [無修正]], 关键词: ['無修正', '全彩', '劇情向', '馬尾', '巨乳', '中文']
> ······
> ```
> 
> 输出中，章节数：[1] ,所有的本子都是1，感觉是章节数获取有问题。

你给的这个case就是单章节的。。。

**Comment by hect0x7** [comment]
试了一下，html确实获取不到多章节

**Comment by hect0x7** [comment]
@liy93 感谢反馈，可以再试下v2.5.24，应该修复了

**Comment by Jackxwb** [comment]
> @liy93 感谢反馈，可以再试下v2.5.24，应该修复了

好像又获取不到章节了
```
jmcomic 112952 --option="./my_jmcomic/option.yml"
[2025-04-06 19:10:30] [MainThread]:【command_line】start downloading...
- using option: [D:\python\mcp\my-mcp-server\my_jmcomic\option.yml]
to be downloaded:
- album: ['112952']
- photo: []
[2025-04-06 19:10:30] [Thread-1 (<lambda>)]:【html】https://18comic-rajang.cc/album/112952
[2025-04-06 19:10:31] [Thread-1 (<lambda>)]:【album.before】本子获取成功: [112952], 作者: [二三月そう], 章节数: [1], 总页数: [1685], 标题: [1LDK JK 突然同居?緊貼!?初次H!!? [二三月そう] 1LDK+JK いきなり
同居? 密著!? 初エッチ!!? [禁漫漢化組] [夢之行蹤漢化組]], 关键词: ['純愛', '女高中生', '劇情向', '長篇', '校服', '巨乳', '雙馬尾', '中文', '連載', '禁漫漢化組', '水手服', '禁漫書庫', '纯爱', '同居', '动 
画化', '处女', '剧情向']
[2025-04-06 19:10:31] [Thread-2 (<lambda>)]:【html】https://18comic-rajang.cc/photo/112952
[2025-04-06 19:10:32] [Thread-2 (<lambda>)]:【photo.before】开始下载章节: 112952 (112952[1/1]), 标题: [1LDK JK 突然同居?緊貼!?初次H!!? [二三月そう] 1LDK+JK いきなり同居? 密著!? 初エッチ!!? [禁漫漢化組] 
[夢之行蹤漢化組]], 图片数为[27]

... 省略 ...
```
从网页上看，有52章，第二章的ID为`112953`即使手动使用这个章节，也会重定向回第一章

option.yml
```
client:
  # impl: 客户端实现类，不配置默认会使用JmModuleConfig.DEFAULT_CLIENT_IMPL
  # 可配置:
  #  html - 表示网页端
  #  api - 表示APP端
  # APP端不限ip兼容性好，网页端限制ip地区但效率高
  impl: html
  # impl: api

  # domain: 域名配置，默认是 []，表示运行时自动获取域名。
  # 可配置特定域名，如下：
  # 程序会先用第一个域名，如果第一个域名重试n次失败，则换下一个域名重试，以此类推。
  domain:
    # - 18comic-uc.vip
    # - 18comic-mhws.vip
    # - 18comic-uc.cc
    # - jmcomic-zzz.one
    # - jmcomic-zzz.org
    - 18comic-rajang.cc

  # retry_times: 请求失败重试次数，默认为5
  retry_times: 5
  postman:
    meta_data:
      # proxies: 代理配置，默认是 system，表示使用系统代理。
      # 以下的写法都可以:
      # proxies: null # 不使用代理
      # proxies: clash
      # proxies: v2ray
      # proxies: 127.0.0.1:7890
      # proxies:
      #   http: 127.0.0.1:7890
      #   https: 127.0.0.1:7890
      proxies: null

      # cookies: 帐号配置，默认是 null，表示未登录状态访问JM。
      # 禁漫的大部分本子，下载是不需要登录的；少部分敏感题材需要登录才能看。
      # 如果你希望以登录状态下载本子，最简单的方式是配置一下浏览器的cookies，
      # 不用全部cookies，只要那个叫 AVS 就行。
      # 特别注意！！！(https://github.com/hect0x7/JMComic-Crawler-Python/issues/104)
      # cookies是区分域名的：
      # 假如你要访问的是 `18comic.vip`，那么你配置的cookies也要来自于 `18comic.vip`，不能配置来自于 `jm-comic.club` 的cookies。
      # 如果你发现配置了cookies还是没有效果，大概率就是你配置的cookies和代码访问的域名不一致。
      cookies:
        AVS: null # 这个值是乱打的，不能用
download:
  cache: true # 如果要下载的文件在磁盘上已存在，不用再下一遍了吧？默认为true
  image:
    decode: true # JM的原图是混淆过的，要不要还原？默认为true
    suffix: .jpg # 把图片都转为.jpg格式，默认为null，表示不转换。
  threading:
    # image: 同时下载的图片数，默认是30张图
    # 数值大，下得快，配置要求高，对禁漫压力大
    # 数值小，下得慢，配置要求低，对禁漫压力小
    # PS: 禁漫网页一次最多请求50张图
    image: 30
    # photo: 同时下载的章节数，不配置默认是cpu的线程数。例如8核16线程的cpu → 16.
    photo: 32



# 文件夹规则配置，决定图片文件存放在你的电脑上的哪个文件夹
dir_rule:
  # base_dir: 根目录。
  # 此配置也支持引用环境变量，例如
  # base_dir: ${JM_DIR}/下载文件夹/
  base_dir: ./download/picture
  rule: Bd_Aid_Pid
plugins:
  after_album:
    # 把章节的所有图片合并为一个pdf的插件
    # 使用前需要安装依赖库: [pip install img2pdf]

    # img2pdf也支持合并整个本子，把上方的after_photo改为after_album即可。
    # https://github.com/hect0x7/JMComic-Crawler-Python/discussions/258
    # 配置到after_album时，需要修改filename_rule参数，不能写Pxx只能写Axx示例如下
    - plugin: img2pdf
      kwargs:
        pdf_dir: ./download/pdf # pdf存放文件夹
        filename_rule: Aid # pdf命名规则，A代表album, name代表使用album.name也就是本子名称
```
