### ISSUE TITLE
[Bug] 使用 img2pdf 插件下载的漫画页顺序错乱

### ISSUE THREAD

**Issue by Qalxry** [hect0x7/JMComic-Crawler-Python#341]
### 注意事项
- [x] 提ISSUE前，请确认你已经在GitHub Issues和Discussions里搜索过类似的问题，并且没找到想要的答案。
- [x] GitHub Actions问题请到置顶的Issue反馈。

### 发生Bug时，你的使用方式？

Python代码

### 你是否在禁漫官方网页或APP，验证过相应的功能是正常的？

测试过，禁漫官方功能正常

### option配置+源码/命令

File: `option.yml`

```yaml
log: true
client:
    impl: api
    retry_times: 5
    postman:
        meta_data:
            proxies: null
            cookies:
                AVS: null
download:
    cache: true
    image:
        decode: true
        suffix: .jpg
    threading:
        image: 10
        photo: 10
dir_rule:
    base_dir: ./data/plugins/fatetrial_jmdownloader/picture
plugins:
    after_album:
        - plugin: img2pdf
          kwargs:
              pdf_dir: ./data/plugins/fatetrial_jmdownloader/pdf
              filename_rule: Aid
```

### 你预期的结果，与实际结果的差别

1. 预期结果：页面顺序和网页/APP端一致
2. 与实际结果的差别：下载下来的PDF页面顺序全乱了

### 其他信息

版本为 pypi 上安装的 2.5.31 。

示例：JM1063503

似乎 `files_of_dir(img_dir)` 返回的是乱序的文件名列表，导致生成的 PDF 页面顺序出错。

我目前用的简易解决方案是给每个章节文件夹下的图片排个序，然后顺序正常。

File: `src/jmcomic/jm_plugin.py` - `Line: 786` 

```python
    def write_img_2_pdf(self, pdf_filepath, album: JmAlbumDetail, photo: JmPhotoDetail):
        import img2pdf

        if album is None:
            img_dir_ls = [self.option.decide_image_save_dir(photo)]
        else:
            img_dir_ls = [self.option.decide_image_save_dir(photo) for photo in album]
        img_path_ls = []

        for img_dir in img_dir_ls:
            imgs = files_of_dir(img_dir)
            if not imgs:
                continue
            img_path_ls += sorted(imgs)  # 添加排序后页面顺序恢复正常

        with open(pdf_filepath, 'wb') as f:
            f.write(img2pdf.convert(img_path_ls))

        return img_path_ls, img_dir_ls
```
