### ISSUE TITLE
[Bug] 使用img2pdf插件合并时如果本子页数太多会导致无法转换为PDF

### ISSUE THREAD

**Issue by CodeChenYi** [hect0x7/JMComic-Crawler-Python#359]
### 注意事项

- [x] 提ISSUE前，请确认你已经在GitHub Issues和Discussions里搜索过类似的问题，并且没找到想要的答案。
- [x] GitHub Actions问题请到置顶的Issue反馈。

### 发生Bug时，你的使用方式？

Python代码

### 你是否在禁漫官方网页或APP，验证过相应的功能是正常的？

我要反馈的bug无需验证/不方便验证

### option配置+源码/命令
```yaml
log: true
client:
  impl: api
  postman:
    meta_data:
      proxies: system
download:
  cache: true # 如果要下载的文件在磁盘上已存在，不用再下一遍了吧？默认为true
  image:
    decode: true # JM的原图是混淆过的，要不要还原？默认为true
    suffix: .jpg # 把图片都转为.jpg格式，默认为null，表示不转换。
  threading:
    image: 45
    photo: 12
dir_rule:
  base_dir: E:/JM/books
  rule: Bd_Atitle_Pindex
plugins:
  after_album:
    - plugin: img2pdf
      kwargs:
        pdf_dir: E:/JM/pdf # pdf存放文件夹
        filename_rule: Aname # pdf命名规则，A代表album, name代表使用album.name也就是本子名称
```
#### 源码
```python
import jmcomic  # 导入此模块，需要先安装.
# 创建配置对象
option = jmcomic.create_option_by_file('D:\ProjectCode\PythonCode\JM-PDF\config.yml')
# # 使用option对象来下载本子
jmcomic.download_album(602129, option)
```
#### 错误信息

[2025-03-24 23:18:07] [<lambda>_thread_pool_executor_8]:【photo.after】章节下载完成: [1041362] (602129[80/92])
[2025-03-24 23:18:07] [MainThread]:【album.after】本子下载完成: [602129]
[2025-03-24 23:18:07] [MainThread]:【plugin.invoke】调用插件: [img2pdf]
[2025-03-24 23:18:09] [MainThread]:【plugin.error】插件 [img2pdf]，运行遇到未捕获异常，异常信息: [Page size must be between 3 and 14400 PDF units]
