### ISSUE TITLE
最近有人遇到html接口一直爆301的情况吗？

### ISSUE THREAD

**Issue by softmanmaker** [hect0x7/JMComic-Crawler-Python#418]
这两天不知道为啥，html接口完全没法使用，总会在getAlbumDetail时报301，然后获取失败。切换域名不起作用，甚至通过cookie登录也没用。我的电脑也没开代理，cookie也是和域名对应的，但是连不需要登陆就能看的本子信息都获取不到，只能fallback到api。
想问一下最近还有别人有这个问题吗？

**Comment by hect0x7** [comment]
我用18comic.vip没问题

**Comment by hect0x7** [comment]
试试代理+18comic.vip，不带任何cookies

**Comment by softmanmaker** [comment]
我去试试，之前都没开代理

**Comment by softmanmaker** [comment]
不行，还是爆，而且看响应速度应该不是超时。
我option这么写的
```
client:
  cache: null
  domain: []
  impl: html
  postman:
    meta_data:
      headers: null
      impersonate: chrome110
      proxies: {}
    type: cffi
  retry_times: 5
dir_rule:
  base_dir: ${JM_PATH}/manga
  rule: Bd_Aid_Pindex
download:
  cache: true
  image:
    decode: true
    suffix: .jpg
  threading:
    image: 20
    photo: 4
log: false
version: "2.1"
```
