### ISSUE TITLE
[Bug] 针对#415更新的python f-string功能，在使用zip文件打包插件时发现功能未实装于插件中

### ISSUE THREAD

**Issue by AXIS5hacker** [hect0x7/JMComic-Crawler-Python#426]
### 请确认注意事项

- [x] 你已经在GitHub Issues和Discussions里搜索过类似的问题，并且没找到想要的答案。
- [x] 你使用的是最新的jmcomic版本
- [x] 非GitHub Actions类问题（此类问题请专门到置顶的Issue反馈）

### 发生Bug时，你的使用方式？

Python代码

### 你是否在禁漫官方网页或APP，验证过相应的功能是正常的？

我要反馈的bug无需验证/不方便验证

### 代码/option配置

以下是我的config配置:

```
client:
  cache: null
  domain: []
  impl: api
  postman:
    meta_data:
      headers: null
      impersonate: chrome110
      proxies:
        http: 127.0.0.1:7897
        https: 127.0.0.1:7897
    type: cffi
  retry_times: 5
dir_rule:
  base_dir: D:/jmdownloader/downloads # 配置下载路径
  rule: Bd/[{Pid}] {Ptitle} 
download:
  cache: true
  image:
    decode: true
    suffix: .png # 下载图片格式, null为保留原格式
  threading:
    image: 40 # max image downloads at the same time, capped to 50
    photo: 32
log: true
plugins:
  valid: log
  after_album:
    - plugin: zip # 压缩文件插件
      kwargs:
        level: photo # 按照章节，一个章节一个压缩文件
        filename_rule: [{Pid}] {Ptitle}  # 压缩文件的命名规则
        zip_dir: D:/jmdownloader/downloads # 压缩文件存放的文件夹
        delete_original_file: true # 压缩成功后，删除所有原文件和文件夹
version: '2.1'
```

若上述yaml配置存在语法错误情况，敬请指出。

### 描述bug现象（你预期的结果，与实际结果的差别）

在zip plugin中指定filename_rule为#415中提出的new feature支持的python字符串格式时(filename_rule: [{Pid}] {Ptitle})，发生如下错误:
Traceback (most recent call last):
  File "D:\jmdownloader\main.py", line 195, in <module>
    option = jmcomic.create_option_by_file('./configs/config1.yml')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\jmcomic\api.py", line 112, in create_option_by_file
    return JmModuleConfig.option_class().from_file(filepath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\jmcomic\jm_option.py", line 371, in from_file
    dic: dict = PackerUtil.unpack(filepath)[0]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\common\base\packer.py", line 178, in unpack
    return packer.unpack(filepath, clazz), packer
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\common\base\packer.py", line 37, in unpack
    return self.with_file(filepath,
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\common\base\packer.py", line 57, in with_file
    return visitor(f, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\common\base\packer.py", line 76, in load
    return yaml.load(fp, yaml.SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\yaml\composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\yaml\composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\yaml\parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "./configs/config1.yml", line 31, column 9
expected <block end>, but found '{'
  in "./configs/config1.yml", line 32, column 32

推测为新的文件名决定机制未实装于zip插件导致的

### 其他可提供的信息

![Image](https://github.com/user-attachments/assets/183ea7db-3a39-4e8b-af3d-ead7be480ab7)

**Comment by hect0x7** [comment]
很明显这是yml语法错误，filename_rule前后要带上''

**Comment by AXIS5hacker** [comment]
根据你指出的yaml语法错误，对我的yaml配置进行了修正。

## 代码/option配置

以下是我的config配置:

```
client:
  cache: null
  domain: []
  impl: api
  postman:
    meta_data:
      headers: null
      impersonate: chrome110
      proxies:
        http: 127.0.0.1:7897
        https: 127.0.0.1:7897
    type: cffi
  retry_times: 5
dir_rule:
  base_dir: D:/jmdownloader/downloads # 配置下载路径
  rule: Bd/[{Pid}] {Ptitle} 
download:
  cache: true
  image:
    decode: true
    suffix: .png # 下载图片格式, null为保留原格式
  threading:
    image: 40 # max image downloads at the same time, capped to 50
    photo: 32
log: true
plugins:
  valid: log
  after_album:
    - plugin: zip # 压缩文件插件
      kwargs:
        level: photo # 按照章节，一个章节一个压缩文件
        filename_rule: '[{PID}] {Ptitle}'  # 压缩文件的命名规则
        zip_dir: D:/jmdownloader/downloads # 压缩文件存放的文件夹
        delete_original_file: true # 压缩成功后，删除所有原文件和文件夹
version: '2.1'
```

## 描述bug现象（你预期的结果，与实际结果的差别）
此时的报错变为:

[2025-04-21 21:58:51] [Thread-1 (<lambda>)]:【plugin.invoke】调用插件: [zip]
[2025-04-21 21:58:51] [Thread-1 (<lambda>)]:【plugin.error】插件 [zip]，运行遇到未捕获异常，异常信息: ['NoneType' object has no attribute 'get_properties_dict']
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\jmcomic\jm_option.py", line 554, in call_all_plugin
    self.invoke_plugin(pclass, kwargs, extra, pinfo)
  File "C:\Python311\Lib\site-packages\jmcomic\jm_option.py", line 597, in invoke_plugin
    self.handle_plugin_unexpected_error(e, pinfo, kwargs, plugin, pclass)
  File "C:\Python311\Lib\site-packages\jmcomic\jm_option.py", line 627, in handle_plugin_unexpected_error
    raise e
  File "C:\Python311\Lib\site-packages\jmcomic\jm_option.py", line 585, in invoke_plugin
    plugin.invoke(**kwargs)
  File "C:\Python311\Lib\site-packages\jmcomic\jm_plugin.py", line 310, in invoke
    zip_path = self.get_zip_path(None, photo, filename_rule, suffix, zip_dir)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\jmcomic\jm_plugin.py", line 379, in get_zip_path
    filename = DirRule.apply_rule_directly(album, photo, filename_rule)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\jmcomic\jm_option.py", line 199, in apply_rule_directly
    return cls.apply_rule_solver(album, photo, cls.get_rule_solver(rule))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\jmcomic\jm_option.py", line 195, in apply_rule_solver
    return func(*detail)
           ^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\jmcomic\jm_option.py", line 159, in format_path
    return fix_windir_name(rule.format(**album.get_properties_dict(), **photo.get_properties_dict())).strip()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_properties_dict'

根据报错信息确定是新的文件名决定机制未实装于zip插件导致的。

## 其他可提供的信息

![Image](https://github.com/user-attachments/assets/48999ed3-5033-4dda-9343-cf6fb3a48776)
