### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by Gpan666** [hect0x7/JMComic-Crawler-Python#437]
### 新功能请求

想要在zip插件使用的时候自动创建个漫画标题的文件夹，并让压缩包放在这个文件夹里面。不知道能不能做到。

**Comment by hect0x7** [comment]
v2.6.0 已支持这样做，请尝试使用新的dir_rule配置项：
```yml
plugins:
  after_photo:
    - plugin: zip
      kwargs:
        level: photo
        dir_rule: # 新配置项，可取代旧的zip_dir和filename_rule
          base_dir: D:/jmcomic-zip
          rule: 'Bd / {Atitle} / [{Pid}]-{Ptitle}.zip'  # 设置压缩文件夹规则，中间Atitle表示创建一层文件夹，名称是本子标题。[{Pid}]-{Ptitle}.zip 表示压缩文件的命名规则
```
