### ISSUE TITLE
[Feature] 将2.6.0版本的新zip插件中encrypt参数的配置方法写入文档

### ISSUE THREAD

**Issue by AXIS5hacker** [hect0x7/JMComic-Crawler-Python#441]
### 新功能请求

在看了更新的zip插件之后，发现该插件多了个参数encrypt，且该参数要求输入一个字典。在当前版本的使用文档中，我没找到该参数的配置方法，看源代码才弄明白这个参数需要写什么内容，**建议把encrypt参数的配置方法写入文档**。

可以在该插件的用法部分写上如下例子:
```
配置zip加密压缩时:
after_album:
    - plugin: zip # 压缩文件插件
      kwargs:
        level: photo # 按照章节，一个章节一个压缩文件
        filename_rule:  # 压缩文件的命名规则
        zip_dir:  # 压缩文件存放的文件夹
        delete_original_file: true # 压缩成功后，删除所有原文件和文件夹
        encrypt:
            impl: zip
            type: # 为random则为随机密码，其他则需要指定密码
            password: # 密码
```
```
配置7z加密压缩时:
after_album:
    - plugin: zip # 压缩文件插件
      kwargs:
        level: photo # 按照章节，一个章节一个压缩文件
        filename_rule:  # 压缩文件的命名规则
        zip_dir:  # 压缩文件存放的文件夹
        delete_original_file: true # 压缩成功后，删除所有原文件和文件夹
        suffix: '7z'
        encrypt:
            impl: 7z
            password: # 密码
```

另外，我试用了一下7z压缩功能，在使用时我发现了两个问题：
1. 指定压缩包格式为7z时(encrypt参数输入{impl:7z}时)，**密码不能为空** (看了下代码逻辑后发现，只要encrypt参数非空则必须有密码)
2. 由于7z压缩包不支持压缩包注释，因此在指定密码为随机时，**无法将随机密码附着至压缩包，会导致压缩之后连压缩者本人也不知道密码的情况（日志输出的密码也可能会被后续日志刷掉）**。因此，这里建议，在使用7z压缩时，禁用使用随机密码的情况。

**Comment by hect0x7** [comment]
文档这块，确实有点偷懒没写😂
7z+随机密码这个点，我自测的时候也是去日志里找密码，感觉也还行，我觉得功能可以留着，文档里可以做一下提醒。

**Comment by AXIS5hacker** [comment]
然后那个使用7z压缩方式，密码不能为空的问题你最好也处理一下

**Comment by hect0x7** [comment]
> 然后那个使用7z压缩方式，密码不能为空的问题你最好也处理一下

这个我觉得也没啥问题，因为encrypt这个配置项就是用来配置加密功能的，如果密码为空就无所谓加密了。所以type和password二选一必填。
不过这样倒也会有一个问题，就是用户单纯想用7z格式压缩，就实现不了了。这个我觉就看有没有这样的使用场景反馈吧

**Comment by AXIS5hacker** [comment]
然后我这边也发现一个事,就是在encrypt参数这么配置的话：

encrypt:
    password:

即有password字段但不填的情况，也是可以的，此时的密码会自动设为None（字符串）

**Comment by hect0x7** [comment]
还真是，str(None)='None'

**Comment by AXIS5hacker** [comment]
所以说你那个使用文档啥时候更新?
比如给zip插件那边的文档加上dir_rule的部分以及encrypt部分的使用方法

**Comment by hect0x7** [comment]
如果你愿意的话也欢迎帮我完善文档

**Comment by hect0x7** [comment]
> 刚刚提了个文档pr，你先看一下行不行

可以👍

**Comment by AXIS5hacker** [comment]
![Image](https://github.com/user-attachments/assets/d2679a13-009d-476a-8f69-e25f3107279b)
实测，在指定7z压缩方式时，加入文件后缀名配置还是有必要的，不然会出现后缀是zip但内容是7z的情况

另：目前你的7z实现方式为：仅加密，不压缩（算法是Copy）

然后我这边有个新发现，当dir_rule配置项存在时，**会使filename_rule, zip_dir, suffix 三个配置项全部无效化**。因此，当使用dir_rule配置时，**需要写上文件后缀，否则会生成一个无后缀名的压缩包**：

配置代码:
```YAML
after_album:
    - plugin: zip # 压缩文件插件
      kwargs:
        level: photo # 按照章节，一个章节一个压缩文件
        filename_rule: '[{Pid}] {Ptitle}' # 压缩文件的命名规则
        zip_dir: D:/jmdownloader/downloads # 压缩文件存放的文件夹
        dir_rule:
          base_dir: D:/jmdownloader/downloads # 配置下载路径
          rule: 'Bd/{Aid}/[{Pid}] {Ptitle}'
        
        delete_original_file: true # 压缩成功后，删除所有原文件和文件夹
        
        encrypt:
            password: TestPassw0rd1
```

输出压缩包：
![Image](https://github.com/user-attachments/assets/da53343c-6408-4895-a569-e3b45e1dd85a)

实测，采用这种配置时，生成的压缩包**无后缀名**，在rule这个字符串中显式写上后缀才会有后缀名。这里建议修一下，让dir_rule配置项存在时，suffix配置项依然要起作用。
